"""
Aegis — Marketplace

Lets the user browse and explicitly choose what to install, rather than
features silently downloading on first use.

Automation Tools: capabilities that need a native download. Voice
transcription used to be here too, but its model is small and universal
enough that it now ships inside the app bundle itself instead, see
app/core/transcription.py's module docstring.
"""

from typing import Dict, List, Optional

TOOLS_CATALOG = [
    {
        "id": "document_extraction",
        "name": "Document Extraction",
        "description": (
            "Pulls plain text out of PDF, DOCX, PPTX, Markdown, TXT/CSV, and "
            "XLSX files — the same extractor Aegis's own document upload and "
            "the Workflows canvas's Extract node already use. PDF/DOCX work "
            "out of the box; everything else installs on demand below."
        ),
        "category": "Extraction",
        "size_estimate": "Install-on-demand",
        "status_endpoint": None,
    },
    {
        "id": "media_transcription",
        "name": "Audio/Video Transcription",
        "description": (
            "Transcribes speech in a local audio or video file to text, "
            "entirely on-device — a Workflow's own Media tool node, or the "
            "same bundled model the chat composer's mic button already uses."
        ),
        "category": "Extraction",
        "size_estimate": "See Media Extraction below",
        "status_endpoint": None,
    },
    {
        "id": "ocr_extraction",
        "name": "Image OCR",
        "description": (
            "Pulls printed or on-screen text out of an image — a scanned "
            "page, a screenshot, a photo of a document. Install an engine "
            "from the Media Extraction category below to use it."
        ),
        "category": "Extraction",
        "size_estimate": "See Media Extraction below",
        "status_endpoint": None,
    },
]

_STATUS_CHECKS = {
    "media_transcription": lambda: True,
    "ocr_extraction": lambda: True,
}


def _document_extraction_catalog() -> List[Dict]:
    """
    One tool-catalog entry per (format, engine) pair in
    app.core.extraction_engines' registry — e.g. "pdfplumber" for PDF, or
    "mammoth" for DOCX — each carrying `format`/`engine_id` on top of the
    normal tool shape. These are what a Workflow's Extract node's config
    panel actually reads (WorkflowsView.tsx's fetchExtractionEngines
    filters GET /api/marketplace/tools for exactly `format` + `engine_id`
    present) to offer a per-format engine choice — the plain
    "document_extraction" entry in TOOLS_CATALOG above only exists as the
    Marketplace page's own single summary card for the capability as a
    whole, it carries neither field. id is prefixed "extract_" so
    list_tools's install/uninstall routing (app.api.marketplace) can tell
    these apart from the plain TOOLS_CATALOG entries above without
    string-parsing engine_id, which can itself contain underscores.
    """
    from app.core.extraction_engines import ENGINES

    out = []
    for fmt, engines in ENGINES.items():
        for engine in engines:
            out.append({
                "id": f"extract_{fmt}_{engine['id']}",
                "name": engine["name"],
                "description": engine["description"],
                "category": "Extraction",
                "format": fmt,
                "engine_id": engine["id"],
                "default": engine.get("default", False),
                "pip_package": engine.get("pip_package"),
                "size_estimate": "Built in" if engine.get("pip_package") is None else "Install-on-demand",
                "status_endpoint": None,
            })
    return out


def list_tools() -> List[Dict]:
    """Merges TOOLS_CATALOG with each tool's live install status. Every
    extraction engine (id prefixed "extract_", generated by
    _document_extraction_catalog) reflects a real, per-format opt-in
    preference (app.core.extraction_engines.is_engine_enabled) — a
    format's own default is always installed; every other engine starts
    NOT installed until the user opts in from here, which (for anything
    needing a real pip package) also triggers a real install — see
    app.api.marketplace's install_tool."""
    from app.core.extraction_engines import is_engine_enabled

    out = []
    for tool in TOOLS_CATALOG + _document_extraction_catalog():
        entry = dict(tool)
        check = _STATUS_CHECKS.get(tool["id"])
        if check:
            entry["installed"] = check()
        elif "format" in tool and "engine_id" in tool:
            entry["installed"] = is_engine_enabled(tool["format"], tool["engine_id"])
        else:
            entry["installed"] = tool["id"].startswith("extract_")
        out.append(entry)
    return out


def find_extraction_entry(tool_id: str) -> Optional[Dict]:
    """Looks up one _document_extraction_catalog() entry by its composite
    id (e.g. "extract_pdf_pdfplumber") — used by the generic Marketplace
    install/uninstall routes to recover the real (format, engine_id) pair
    without string-parsing the id, since an engine_id can itself contain
    underscores (e.g. "pdfminer_six")."""
    return next((e for e in _document_extraction_catalog() if e["id"] == tool_id), None)
