"""
Aegis — Marketplace

Lets the user browse and explicitly choose what to install, rather than
features silently downloading on first use (e.g. web scraping used to
download a ~95MB headless Chromium the first time someone clicked "Scrape a
Web Page" — now that install only happens when the user picks it here).

Automation Tools: capabilities that need a native download (currently just
Playwright-based web scraping — voice transcription used to be here too,
but its model is small and universal enough that it now ships inside the
app bundle itself instead, see app/core/transcription.py's module
docstring). Install/status is delegated to whatever module actually owns
that capability (app.core.scraper) rather than duplicated here.
"""

from pathlib import Path
from typing import List, Dict

from app.core.scraper import is_chromium_installed

TOOLS_CATALOG = [
    {
        "id": "playwright_scraper",
        "name": "Web Scraping",
        "description": (
            "Lets Aegis open a real headless browser to scrape any web page — "
            "including JavaScript-heavy sites — and add its content to your "
            "chat as a searchable document."
        ),
        "category": "Automation",
        "size_estimate": "~95 MB, downloaded once",
        "status_endpoint": "/api/scrape/status",
    },
    {
        "id": "document_extraction",
        "name": "Document Extraction",
        "description": (
            "Pulls plain text out of PDF, DOCX, PPTX, Markdown, TXT/CSV, and "
            "XLSX files — the same extractor Aegis's own document upload and "
            "the Workflows canvas's Extract node already use."
        ),
        "category": "Extraction",
        "size_estimate": "Built in",
        "status_endpoint": None,
    },
    {
        "id": "web_extraction",
        "name": "Web Page Extraction",
        "description": (
            "Fetches a static web page and pulls out its main readable text — "
            "no headless browser, so it's fast, but can't render "
            "JavaScript-built pages (the Web Scraping tool above handles those)."
        ),
        "category": "Extraction",
        "size_estimate": "Built in",
        "status_endpoint": None,
    },
    {
        "id": "media_transcription",
        "name": "Audio/Video Transcription",
        "description": (
            "Transcribes speech in a local audio or video file to text, "
            "entirely on-device — the same bundled model the chat composer's "
            "mic button already uses."
        ),
        "category": "Extraction",
        "size_estimate": "Built in",
        "status_endpoint": None,
    },
    {
        "id": "ocr_extraction",
        "name": "Image OCR",
        "description": (
            "Pulls printed or on-screen text out of an image — a scanned "
            "page, a screenshot, a photo of a document — using a small "
            "bundled OCR model."
        ),
        "category": "Extraction",
        "size_estimate": "~15 MB, bundled",
        "status_endpoint": None,
    },
]

_STATUS_CHECKS = {
    "playwright_scraper": is_chromium_installed,
    "web_extraction": lambda: True,
    "media_transcription": lambda: True,
    "ocr_extraction": lambda: True,
}


def _document_extraction_catalog() -> List[Dict]:
    """
    One tool-catalog entry per (format, engine) pair in
    app.core.extraction_engines' registry — e.g. "pdfplumber" for PDF, or
    "mammoth" for DOCX — each carrying `format`/`engine_id` on top of the
    normal tool shape. These are what a Workflow's Extract node's config
    panel actually reads (WorkflowsView.tsx's fetchExtractionEngines
    filters GET /api/marketplace/tools for exactly `format` + `engine_id`
    present) to offer a per-format engine choice — the plain
    "document_extraction" entry in TOOLS_CATALOG above only exists as the
    Marketplace page's own single summary card for the capability as a
    whole, it carries neither field. id is prefixed "extract_" so
    list_tools's installed-status fallback (every one of these ships
    bundled, nothing to download) applies with no per-entry
    _STATUS_CHECKS bookkeeping needed.
    """
    from app.core.extraction_engines import ENGINES

    out = []
    for fmt, engines in ENGINES.items():
        for engine in engines:
            out.append({
                "id": f"extract_{fmt}_{engine['id']}",
                "name": engine["name"],
                "description": engine["description"],
                "category": "Extraction",
                "format": fmt,
                "engine_id": engine["id"],
                "default": engine.get("default", False),
                "size_estimate": "Built in",
                "status_endpoint": None,
            })
    return out


def list_tools() -> List[Dict]:
    """Merges TOOLS_CATALOG with each tool's live install status. Every
    extraction engine (id prefixed "extract_", generated by
    _document_extraction_catalog) is bundled at build time same as the
    other Extraction-category tools, so it's always "installed" — there's
    no per-engine entry to keep in sync with _STATUS_CHECKS by hand."""
    out = []
    for tool in TOOLS_CATALOG + _document_extraction_catalog():
        entry = dict(tool)
        check = _STATUS_CHECKS.get(tool["id"])
        entry["installed"] = check() if check else tool["id"].startswith("extract_")
        out.append(entry)
    return out
